nfd:
  enabled: true

  #sriovNetworkOperator:
  #  enabled: true
  #  # pfNames, linkTypes, isRdma
  #  resources:
  #    - name: sriov_rdma
  #      pfNames: ens11f1
  #      isRdma: true


# NicClusterPolicy CR values:
deployCR: true
ofedDriver:
  deploy: false

rdmaSharedDevicePlugin:
  deploy: true
  resources:
    - name: jf.rdma/roce
      drivers: ["mlx5_core"]
      #ifNames: ["ens11f0", "ens11f1"]

secondaryNetwork:
  deploy: true
  cniPlugins:
    deploy: true
  multus:
    deploy: true
  ipamPlugin:
    deploy: true

# to remove node affinity in multus ds
nodeAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
  - weight: 1
    preference:
      matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: DoesNotExist
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
