nfd:
  enabled: true

sriovNetworkOperator:
  enabled: false
sriovDevicePlugin:
  deploy: false

# NicClusterPolicy CR values:
deployCR: true
ofedDriver:
  deploy: false
  # Find available mofed image from https://catalog.ngc.nvidia.com/containers
  #  version: 23.10-2.1.3.1-10

rdmaSharedDevicePlugin:
  deploy: true
  resources:
    - name: jf_roce
      drivers: ["mlx5_core"]
      #ifNames: ["ens11f0", "ens11f1"]

nvPeerDriver:
  deploy: true

secondaryNetwork:
  deploy: true
  cniPlugins:
    deploy: true
  multus:
    deploy: true
  ipamPlugin:
    deploy: true

# to remove node affinity in multus ds
nodeAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
  - weight: 1
    preference:
      matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: DoesNotExist
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
