apiVersion: mellanox.com/v1alpha1
kind: MacvlanNetwork
metadata:
  name: nad-204
spec:
  networkNamespace: default
  master: "ens2.204"
  mode: "bridge"
  mtu: 4200
  ipam: |
    {
     "type": "whereabouts",
     "range": "10.0.204.0/24",
     "range_start": "10.0.204.3",
     "range_end": "10.0.204.254",
     "gateway": "10.0.204.1"
    }
