apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: nad-204
spec:
  nodeSelector:
    kubernetes.io/hostname: acridc-204
  containers:
  - image: ubuntu:20.04
    name: rdma-test-ctr
    securityContext:
      privileged: true
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        nvidia.com/gpu: 1
        rdma/jf_roce: 1
      requests:
        nvidia.com/gpu: 1
        rdma/jf_roce: 1
    command:
    - sh
    - -c
    - sleep infinity
