apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  annotations:
    k8s.v1.cni.cncf.io/networks: nad2
spec:
  nodeSelector:
    kubernetes.io/hostname: acridc-205
  containers:
  - image: mellanox/rping-test
    name: rdma-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        rdma/rdma_shared_device_a: 1
      requests:
        rdma/rdma_shared_device_a: 1
    command:
    - sh
    - -c
    - sleep infinity
