apiVersion: v1
kind: Pod
metadata:
  name: mp-rdma-test2
  annotations:
    k8s.v1.cni.cncf.io/networks: nad-102
spec:
  nodeSelector:
    kubernetes.io/hostname: acridc-102
  containers:
  - image: mellanox/rping-test
    name: rdma-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      limits:
        jf.rdma/roce: 1
        nvidia.com/gpu: 1
      requests:
        jf.rdma/roce: 1
        nvidia.com/gpu: 1
    securityContext:                                                                                   
      privileged: true
    command: ["/bin/sh", "-c"]
    args: ["apt update && apt install -y python3 vim build-essential wget openssh-server openssh-client  net-tools iputils-ping pciutils iproute2 perftest traceroute; ip route add 10.0.0.0/16 via 10.0.102.1; sleep infinity"]
